### ISSUE TITLE
Question: Using in an NPM project

### ISSUE THREAD

**Issue by YanDoroshenko** [lecbyjak/intelligent-tree-select#5]
How do I use the IntelligentTreeSelectComponent in an NPM-based project?

**Comment by lecbyjak** [comment]
Hi, I am glad that you are interested in this project, but I am still working on it doing some improvements and fixing bugs so that's the reason why I still don't publish it as an NPM package. I will try to do it asap and I will inform you when it will be available.

**Comment by lecbyjak** [comment]
https://www.npmjs.com/package/intelligent-tree-select
