### ISSUE TITLE
npm start Parse error

### ISSUE THREAD

**Issue by YanDoroshenko** [lecbyjak/intelligent-tree-select#6]
`npm start` produces Parse error:
```
.../src/main/webapp/node_modules/intelligent-tree-select/lib/App.css:1
.result-item{
^
ParseError: Unexpected token
```

**Comment by lecbyjak** [comment]
I have published new version so can you try it again? If the problem is not solved can you provide detailed information like your exact `npm start` script and where you import this file. Thx

**Comment by YanDoroshenko** [comment]
@lecbyjak Does not work for me, version `0.2.1`:
```
watchify -o ../../../target/s-pipes-editor-0.1/js/bundle.js -v -d js/app.js


/.../node_modules/react-virtualized-select/styles.css:1
.VirtualSelectGrid {
^
ParseError: Unexpected token
```

```
import { IntelligentTreeSelect } from "intelligent-tree-select";
```

**Comment by lecbyjak** [comment]
Here is a solution.
 https://stackoverflow.com/questions/49110091/unable-to-import-css-with-babel-plugin-react-css-modules-get-parseerror-un or this one 
https://stackoverflow.com/questions/42396478/unable-to-import-css-file-with-es6-syntax-using-grunt-browserify-with-transform
