### ISSUE TITLE
Search string is not getting selected on typing and hitting enter in the dropdown

### ISSUE THREAD

**Issue by sreeja02** [lecbyjak/intelligent-tree-select#75]
Hi Team, 

We are using intelligent-tree-select in the reactjs app. From the below screenshot, if we type 'comp amount' in the search box and hit enter, it should be selected. But its not working. Instead, the value inside onChange handler has only the first value in the from the options. Please suggest a fix
<img width="631" alt="Screenshot 2024-02-09 at 10 34 12 PM" src="https://github.com/lecbyjak/intelligent-tree-select/assets/24984639/1e7046f0-c54e-4a8b-b49c-7f40b954d56f">

**Comment by ledsoft** [comment]
Hi, thanks for reporting this. We'll look into it as soon as possible.

**Comment by ledsoft** [comment]
Should be fixed in 0.11.4. Feel free to reopen if there are still issues with selection via keyboard.

**Comment by sreeja02** [comment]
Thanks @ledsoft .
